name: Deployment

on:
  push:
    branches: [ "main", "workflow/integration" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build the Docker image
      - run: docker build . -t garvxt/epiwatch-app:2.0

      # Login to Docker Hub (public for now)
      - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin

      # Push the image
      - run: docker push garvxt/epiwatch-app:2.0